export const names = {
    NEW_USER: 'NEW_USER',
    USER_LOGGED_IN: 'USER_LOGGED_IN',
    USER_LOGGED_OUT: 'USER_LOGGED_OUT',
    BOOK_ADDED: 'BOOK_ADDED',
    BOOK_SELECTED: 'BOOK_SELECTED',
    BOOK_ISSUED: 'BOOK_ISSUED',
    BOOK_RENEWED: 'BOOK_RENEWED',
    BOOK_RETURNED: 'BOOK_RETURNED',
    BOOK_REVIEWED: 'BOOK_REVIEWED',
    BOOK_AVAILABILITY_UPDATE: 'BOOK_AVAILABILITY_UPDATE',
    BOOK_RETURN_UPDATE: 'BOOK_RETURN_UPDATE'
}